### ISSUE TITLE
Microsoft Store Link is broken

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [CanTalat-Yakan/3DEngine#1]
The button to the microsoft store leads to nowhere, unable to download the engine.

**Comment by EggyStudio** [comment]
Yeah, thats because I submitted a newer build to Microsoft and the link to the privacy policy was wrong it failed. I updated it but it seems I have to resubmit it. I am currently working on another branch to make DX12 work and updated to .net 8and c# 12 finally. When that works, I will resubmit the new build to the store. So it is kinda in maintance

**Comment by guinhx** [comment]
When will new updates come out? Eager to test, in fact, try to better document the project setup process for anyone who wants to contribute.

**Comment by EggyStudio** [comment]
I will hire a freelancer to help me with DX12 very soon. Then I will update everything, including documentation.

**Comment by EggyStudio** [comment]
I've completed the DX12 renderer, updated the Editor, and submitted it to the Microsoft Store. Currently, it's undergoing review. The new version is also available in the Releases section on GitHub.

As the issue has been addressed, I'll be closing this thread.
